### ISSUE TITLE
ROOT installation issue using conda 

### ISSUE THREAD

**Issue by meshoaib** [conda-forge/root-feedstock#110]
Issue:
trying to install root on conda with following command:

conda create -c conda-forge --name myenv root

Following error:
PackagesNotFoundError: The following packages are not available from current channels:

  - root

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
EnvironmentLocationNotFound: Not a conda environment: C:\Users\Lenovo\anaconda3\envs\myenv

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

 active environment : myenv
    active env location : C:\Users\Lenovo\anaconda3\envs\myenv
            shell level : 2
       user config file : C:\Users\Lenovo\.condarc
 populated config files : C:\Users\Lenovo\.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages :
       base environment : C:\Users\Lenovo\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Lenovo\anaconda3\pkgs
                          C:\Users\Lenovo\.conda\pkgs
                          C:\Users\Lenovo\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Lenovo\anaconda3\envs
                          C:\Users\Lenovo\.conda\envs
                          C:\Users\Lenovo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by chrisburr** [comment]
Unfortunately ROOT doesn't support 64-bit Windows builds so I can't provide a conda package for it natively.

I've heard that the Linux build works very well inside Windows Subsystem for Linux so that is probably your best option.
