### ISSUE TITLE
Output in format: Requested package -> Available versions

### ISSUE THREAD

**Issue by jingydz** [conda-forge/root-feedstock#119]
Hi, it appeared something wrong when I install root. Anyone who know it?
$ conda install -c conda-forge root
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages. failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by eguiraud** [comment]
Hi,
given

```
Found conflicts! Looking for incompatible packages. failed
```

it seems that the conda environment you are trying to install ROOT already contains other packages with incompatible dependencies. Installing ROOT in its own environment should work: `conda env create -n cern-root -c conda-forge root`.

**Comment by jingydz** [comment]
@eguiraud Thank you. I got it and it worked. ^.^~
