### ISSUE TITLE
[macOS] `root_config --cflags` incompatible with default compilers

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root-feedstock#13]
On macOS `root_config --cflags` returns `--std=c++17` but the default conda compilers only support `--std=c++1z`. See the CI results of `Exclude broken root_numpy tests` in https://github.com/conda-forge/root_numpy-feedstock/pull/2.

We should either:
 * patch `root-config` to return `--std=c++1z`
 * use C++14 (it's in conda's default `$CXXFLAGS`)

**Comment by henryiii** [comment]
I think c++14 is not a bat idea. It's building with LLVM 4 and that doesn't fully support c++17. If you check the home brew PR, it's only been the last release or maybe two that have supported C++17. So mildly for that idea. However, shouldn't coot-ConfigParser support c++1z if ROOT was built that way? That seems like a bit of a bug.

**Comment by chrisburr** [comment]
The downside is that it becomes inconsistent between Linux and macOS and [clang 4 already supports effectively everything](https://clang.llvm.org/cxx_status.html) but I don't feel strongly either way.

And yeah, that does seem like a bug.

**Comment by henryiii** [comment]
If we can patch it and get it into ROOT, I think I would be for the patch. If not, I think I would still be slightly for c++14.  I can try to take a look into it soon.

**Comment by henryiii** [comment]
The line is here:
```cpp
cxxversionflag="-std=c++@CMAKE_CXX_STANDARD@ "
```

**Comment by henryiii** [comment]
Fixed in root-project/root#3411 .
