### ISSUE TITLE
root conda package for plain x86_64, without SSE 4.2, AVX, ...

### ISSUE THREAD

**Issue by rudolfII** [conda-forge/root-feedstock#134]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

At the current moment it is not possible to run on older x86 cpus:

```
(our_root) [conda@void ~]$ python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT

 *** Break *** <TUnixSystem::DispatchSignals>: illegal instruction
```

**Comment by chrisburr** [comment]
Fixed in 8685960399eeb8a0a2dc0cfdcb3aa07e7f954647
