### ISSUE TITLE
Error compiling a basic standalone C++ program against root-feedstock

### ISSUE THREAD

**Issue by olifre** [conda-forge/root-feedstock#139]
Issue:

Following installation steps from https://iscinumpy.gitlab.io/post/root-conda/ on Ubuntu 20.04 does not yield a working environment in which simple standalone programs can be compiled against ROOT. 

To ease reproduction, I have set up a [GitHub actions workflow](https://github.com/olifre/root-install-test/blob/master/.github/workflows/test-conda-miniconda.yml) which fails. A similar [workflow using Anaconda](https://github.com/olifre/root-install-test/blob/master/.github/workflows/test-conda-anaconda.yml) yields the exact same error messages. 

This uses `ubuntu-latest` and runs the following commands, as described in the blog:
```
sudo apt-get -y install build-essential
wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p ~/miniconda
source ~/miniconda/etc/profile.d/conda.sh
conda create -n my_root_env root -c conda-forge
conda activate my_root_env
make
```
using the minimal `Makefile`:
```make
default:
	g++ -ggdb -Wl,--no-as-needed `root-config --libs --ldflags` `root-config --cflags` analysis.C -o analysis
```
and the minimal program:
```
#define analysis_cxx
#include <TFile.h>

int main() {
  TFile foo("foo.root", "RECREATE");
  return 0;
}
```
This yields the following error:
```
2021-08-09T17:56:26.7686249Z g++ -ggdb -Wl,--no-as-needed `root-config --libs --ldflags` `root-config --cflags` analysis.C -o analysis
2021-08-09T17:56:27.4589561Z In file included from /home/runner/miniconda/envs/my_root_env/x86_64-conda-linux-gnu/include/c++/9.3.0/chrono:41,
2021-08-09T17:56:27.4591544Z                  from /home/runner/miniconda/envs/my_root_env/x86_64-conda-linux-gnu/include/c++/9.3.0/condition_variable:38,
2021-08-09T17:56:27.4592740Z                  from /home/runner/miniconda/envs/my_root_env/include/ROOT/TRWSpinLock.hxx:19,
2021-08-09T17:56:27.4593936Z                  from /home/runner/miniconda/envs/my_root_env/include/TFile.h:38,
2021-08-09T17:56:27.4595050Z                  from analysis.C:2:
2021-08-09T17:56:27.4596737Z /home/runner/miniconda/envs/my_root_env/x86_64-conda-linux-gnu/include/c++/9.3.0/ctime:80:11: error: '::timespec_get' has not been declared
2021-08-09T17:56:27.4597748Z    80 |   using ::timespec_get;
2021-08-09T17:56:27.4598301Z       |           ^~~~~~~~~~~~
2021-08-09T17:56:27.5831766Z make: *** [Makefile:2: default] Error 1
2021-08-09T17:56:27.5842391Z ##[error]Process completed with exit code 2.
```

Is this a usage error? I tried to follow the documentation step-by-step.

**Comment by eguiraud** [comment]
Hi, see the conversation here: https://root-forum.cern.ch/t/error-timespec-get-has-not-been-declared-with-conda-root-package/45712 (in particular the last couple of posts).

**Comment by olifre** [comment]
@eguiraud I've already seen this thread, but this has been in an environment which also added the `default` channel. 
As you see in the commands above and in the linked GitHub actions recipe, I have explicitly selected `conda-forge` during installation in a clean environment, and tried to follow the instructions from the blog:
https://iscinumpy.gitlab.io/post/root-conda/
to the letter. If these do not work (actually, one of my students hit this issue), should we document different "install ROOT with conda from scratch" commands?

**Comment by eguiraud** [comment]
Those instructions should work -- they worked until a month ago, at least.

I can reproduce the problem on my Arch laptop and in an Arch or Ubuntu 20.04 docker container. I cannot reproduce the problem in a `condaforge/miniforge3` docker container.

Also, you don't need ROOT to get compilation errors, this already fails to compile:

```cpp
#include <chrono>
int main() {}
```
with different failure modes depending on whether `-std=c++14` or `-std=c++17` is used (for `c++17` the error message is the same as what you report, which makes sense since ROOT coming from conda would set the standard to `c++17`, while for `c++14` there are linker errors).

So from what I understand this is a new problem, due to some mismatch between the host environment and the conda(-forge) environment, and it's not strictly a problem of the ROOT conda package.

Should this be reported upstream @chrisburr @henryiii ?

Here's a Dockerfile that reproduces the issue:

```
FROM ubuntu:20.04

RUN apt-get update && apt-get -y install build-essential wget
RUN wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b -p ~/miniconda
RUN echo '#include <chrono>' > 'test.cpp'
RUN echo -e '#!/bin/bash \n\
source ~/miniconda/etc/profile.d/conda.sh \n\
set -x \n\
conda create -n my_root_env root -c conda-forge\n\
conda activate my_root_env\n\
g++ -c -std=c++17 test.cpp' > repro.sh
RUN bash repro.sh
```

**Comment by olifre** [comment]
@eguiraud Thanks, I did not think of testing the basic case without ROOT, very good idea! 

For me, it also means I'll keep that [repository](https://github.com/olifre/root-install-test) around to automatedly check regularly if this use case works (and I will also add your more minimal reproducer there) so I can catch these kind of issues earlier and report them / advice students if they hit this. 
In case you want to add these / similar tests here, feel free to copy anything you deem useful ;-).

**Comment by eguiraud** [comment]
Strict channel priority will be the default in future conda versions (starting from conda 5 as it's a backward-incompatible change).

In the meanwhile I [added instructions to the ROOT docs](https://github.com/root-project/web/pull/643) to add the setting when installing ROOT via conda.

@henryiii maybe [your famous blog post](https://iscinumpy.gitlab.io/post/root-conda/) should also be updated.
