### ISSUE TITLE
Mark root as conflicting with root5

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root-feedstock#14]
`root` and `root5` can't be installed in the same environment so they should be marked as conflicting in the `meta.yaml`.

The old `root` binaries should be marked as broken or have their metadata patched in [conda-forge-repodata-patches-feedstock](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) to ensure the solver doesn't pick an old build.

**Comment by henryiii** [comment]
Is root 5 maintained? I don't thing it's working in the new stack. Would be nice if it was. Agree should the conflict mark.

**Comment by chrisburr** [comment]
> Is the root 5 conda package maintained?

It's only a year old but yeah I didn't realise it hadn't been migrated.

**Comment by henryiii** [comment]
It also has several issues, hardcoded number of threads in build, is Python 2.7 only, etc. I've added an exclusion but hopefully no one will try to use both.

I'll make a PR once conda-forge-pinning is updated.
