### ISSUE TITLE
Status of builtin_pyroot / standalone_pyroot

### ISSUE THREAD

**Issue by wshanks** [conda-forge/root-feedstock#146]
I was looking through the recipe and noticed the support for a standalone pyroot package which is currently disabled. I was curious if that is something you are still pursuing and if something like your patch for the cmake configuration related to this could be upstreamed.

When possible, I use the conda-forge root packages and am very happy with all your work on them. There are some pipelines where I can't use conda and it annoys me that I have not found a better way to support more than one Python version than rebuilding all of root for each one. I have played around with extracting the pyroot makefile in the past ([here](https://github.com/wshanks/pyroot_link_to_binary)), but that was a hack. Having support in the cmake files would be much better. Personally, I don't know cmake that well.

(Sorry if there is a better forum to ask this).

**Comment by henryiii** [comment]
I'm currently working on a proposal to get funded to work on scikit-build, and a pip-installable ROOT package is part of that proposal. If you have nice use cases, that would be great to add in support of the proposal. :)

**Comment by wshanks** [comment]
pip-installable ROOT would be nice. I feel like I am probably an unusual
ROOT user. A non-HEP (and non-public) project I work on uses ROOT as a
plotting library. When ROOT was chosen, matplotlib was found to be too
slow, and bokeh, pyqtgraph, and plotly had other issues (did not have good support for writing to disk, had performance bottlenecks, or were not open source at the time; I think these issues have somewhat been addressed but I haven't tried comparing plotting performance recently).

To install ROOT, I usually install Python and build ROOT from source
pointing at that installation of Python. The PyROOT part is quick to compile, so when I
update ROOT or Python I wish I had a better method than recompiling all of
ROOT. I am trying out compiling ROOT in a multi-stage container with PyROOT disabled in one stage and then rerunning cmake and building again with PyROOT enabled in a second stage. It feels a little bit hacky, but it seems to work.

Being able to pip install PyROOT for a specific version of ROOT would be
nice. Being able to pip install all of ROOT would be nice too (that would be a pretty big package and have more compile options to worry about).

Nice interview on Talk Python recently :slightly_smiling_face:
