### ISSUE TITLE
Disable RooFit banner with __ROOFIT_NOBANNER option

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/root-feedstock#160]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Any use of RooFit will cause it to print the RooFit copyright banner to screen.

```console
$ python -c 'from ROOT import RooFit'  # Get banner

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt
```

This is generally not desirable. However, the banner can be disabled for a build of ROOT by adding the RooFit compile option `__ROOFIT_NOBANNER` as input to the `CMAKE_CXX_FLAGS` CMake option. So for example, this might look like adding

```diff
diff --git a/recipe/build.sh b/recipe/build.sh
index 047e3a8..56896f5 100755
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -194,6 +194,7 @@ CMAKE_PLATFORM_FLAGS+=("-Dmlp=ON")
 CMAKE_PLATFORM_FLAGS+=("-Dopengl=ON")
 CMAKE_PLATFORM_FLAGS+=("-Dpythia8=ON")
 CMAKE_PLATFORM_FLAGS+=("-Droofit=ON")
+CMAKE_PLATFORM_FLAGS+=("-DCMAKE_CXX_FLAGS=-D__ROOFIT_NOBANNER")
 CMAKE_PLATFORM_FLAGS+=("-Droot7=ON")
 CMAKE_PLATFORM_FLAGS+=("-Dspectrum=ON")
 CMAKE_PLATFORM_FLAGS+=("-Dsqlite=ON")
```

just after

https://github.com/conda-forge/root-feedstock/blob/d70394c84e874a5f71f98fa62b9b1d3659b0a91f/recipe/build.sh#L196

The resulting build now longer has the banner printed

```console
$ python -c 'from ROOT import RooFit' # No banner now
```

c.f. https://gitlab.cern.ch/atlas-amglab/atlstats/-/merge_requests/63 for more details.

If this is of interest, I have this already implemented in my fork and can open a PR.

<br/>
Environment (<code>conda list</code>):
<details>

Not relevant as feature request.

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

Not relevant as feature request.

```
$ conda info

```
</details>

**Comment by chrisburr** [comment]
I completely agree with you that this banner is unreasonably verbose.

Have you tried proposing upstream to change the default? (or maybe even remove it entirely)

**Comment by matthewfeickert** [comment]
> I completely agree with you that this banner is unreasonably verbose.

:rocket: 

> Have you tried proposing upstream to change the default? (or maybe even remove it entirely)

Yeah, I'm going to attempt to do this, but I figured that will for sure not be fast and to get approved and in. So while I work on that (and trying to write up a bit of an argument for it beyond "this isn't necessary anymore") I thought I'd see if you all wanted it.

**Comment by matthewfeickert** [comment]
@chrisburr ROOT Issue 9954 is open now. :slightly_smiling_face:

**Comment by chrisburr** [comment]
Closing as this was added to the build of 6.26.0
