### ISSUE TITLE
ROOT notebook

### ISSUE THREAD

**Issue by henryiii** [conda-forge/root-feedstock#17]
The command `root --notebook` seems to open the system jupyter notebook instead of ROOT, and crashes because metakernel is not installed (in my case). If notebook and metakernel are added, this works. Question: Does ROOT expect JupyterLab, or is it reading something in my environement? I ket a module import error from not finding JupyterLab, but everything still works. I'm pretty sure jupyterlab does not need to be in the runtime deps.

Also, does ROOT properly install its kernel, or is there a way to install it? Other environments allow you to install a kernel and use them without activating the environment, could PyROOT and even C++ ROOT do the same? Just a thought.

Current resolution: Add notebook and metakernel to the runtime deps. I'll also fix a couple of patch notes to indicate they can be removed with ROOT 6.16.02.

**Comment by chrisburr** [comment]
Locally I get:
```bash
$ root --notebook
Error starting ROOT notebook -- please check that Jupyter is installed
```
Running `conda install jupyter metakernel` makes it work as expected for me.

[Behind the scenes](https://github.com/root-project/root/blob/893168f72e71bd3ce290bd42187c9a03e45269ad/main/src/nbmain.cxx#L209) it seem's ROOT generates `$HOME/.rootnb` runs:
```bash
JUPYTER_CONFIG_DIR=$HOME/.rootnb JUPYTER_PATH=$HOME/.rootnb jupyter notebook
```
The contents of `$HOME/.rootnb` is installation dependent and ROOT assumes the contents is valid once it's created. Of course that means different builds, conda environments or package managers will conflict. 🙄

### Suggestion for patching

Installing ROOT should create two new directories:

* `share/jupyter/kernels/root/` containing the kernel that can be used from normal Jupyter or JupyterLab
* `share/rootnb/` contains what is currently put into `$HOME/.rootnb` (without the `LD_LIBRARY_PATH`, `PATH`, `PYTHONPATH` changes)

`nbmain.cxx` can then be replaced with a more package manager friendly version that will set `JUPYTER_CONFIG_DIR` and `JUPYTER_PATH` to `$PREFIX/share/rootnb`.

**Comment by chrisburr** [comment]
From quickly checking it seems `root --notebook`, `jupyter notebook` and `jupyter-lab` all work correctly now so this can be closed.
