### ISSUE TITLE
Need a specific combination of ROOT and python

### ISSUE THREAD

**Issue by angelcampoverde** [conda-forge/root-feedstock#185]
### Comment:

Hi,

I am trying to install ROOT, but I need a specific version of python with it. I am doing

```
conda create -c conda-forge --name root_env root python=3.8.6
```

but it gets stuck. I am also trying:

```
conda create -n root_env
conda activate root_env
conda install root python=3.8.6
```
but it also gets stuck, both in `Solving environment`. Is it possible to install ROOT for this specific version of python? 

Cheers.

**Comment by chrisburr** [comment]
Why do you need a specific patch release of Python? I'd be very surprised if `3.8.*` wasn't good enough.

Also using [mamba](https://github.com/mamba-org/mamba/#mamba) will likely help with the slow solve issue.

**Comment by angelcampoverde** [comment]
> Why do you need a specific patch release of Python? I'd be very surprised if `3.8.*` wasn't good enough.

Honestly, this happened a while ago and by now I am not sure why I needed that, in any case, I do not need it anymore.
> 
> Also using [mamba](https://github.com/mamba-org/mamba/#mamba) will likely help with the slow solve issue.

Ok, I will try to move to mamba, thanks. I closing the issue.

**Comment by angelcampoverde** [comment]
Hi @chrisburr ,

So I keep having this problem with the lack of ROOT builds for python 3.10. I am trying to use zfit and there seem to be a small range of packages that I can use with it. If I:

1. Make a conda environment.
2. Install zfit with pip and let zfit pick whatever versions it needs.
3. Install root from conda-forge

ROOT does get installed, but I cannot use it from inside python, because of the version I am using, 3.10.6. You can see the list of packages in my environment in [pip_list.txt](https://github.com/conda-forge/root-feedstock/files/9978492/pip_list.txt). Now I have to downgrade everything to 3.8 and hope that zfit is ok with it. However I have a 3.8 environment already and I seem not to be able to use zfit there for other reasons that I cannot understand.

In any case, I do believe it is convenient if we can have ROOT built for at least two versions of python and I believe it would not be a lot of work to get that.

Cheers

**Comment by angelcampoverde** [comment]
Hi @chrisburr 

Yes, you are right there are bulds for 3.8-3.11. I just checked and managed to get a few environments for different python versions. Sorry for the noise, I will close the issue again.

Cheers.
