### ISSUE TITLE
Remove macOS SDK requirement

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root-feedstock#19]
It seems we can fix compilation on macOS without requiring users to download the 10.9 SDK! 🎉 

I won't have time to fix it for a few days. If anyone else has time I can explain what is needed else this can act as a reminder.

**Comment by chrisburr** [comment]
This is now progressing thanks to https://github.com/conda-forge/conda-forge.github.io/issues/865#issuecomment-533090050. Conda can now link against any macOS SDK provided the backwards compatibility of the binaries isn't a concern. The compilers package should be updated before rebuilding this package. We can also update to using clang 8 at the same time to get full C++17 support.

Looking further forwards, there is a discussion on making an open macOS SDK which conda could distribute, completely removing the need for the command line tools to be installed. https://github.com/conda-forge/conda-forge.github.io/issues/865

**Comment by isuruf** [comment]
@chrisburr, do you mind removing the caveats in the README about OSX 10.9

**Comment by arpanda** [comment]
I am getting the warning:
```
WARNING: Compiling likely won't work unless you download the macOS 10.9 SDK and set CONDA_BUILD_SYSROOT.
You can probably ignore this warning and just omit + or ++ when executing ROOT macros.
```
And while one root dependent software, I am getting the below error:
`dyld: Library not loaded: @rpath/libreadline.8.dylib`

So is it mandatory to use maOS 10.9 SDK to get the full functionality of ROOT.

**Comment by henryiii** [comment]
This package has not yet been rebuilt, compilers needs to be rebuilt first, so I don't think anything has changed for the root package itself yet.
