### ISSUE TITLE
limits.h / __GLIBC_USE issue linking root (include path problem?)

### ISSUE THREAD

**Issue by willsALMANJ** [conda-forge/root-feedstock#2]
Issue: I am very excited about a conda ROOT package (and I don't how many hours I have spent compiling ROOT over the years). I am encountering an error when I try to install the root package. I don't know exactly what is happening so I show the log of the install below. It seems like it might be mistakenly using `/usr/include/limits.h` instead of the one in the vendored cling inside of the root package?

<details>
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/user/conda/envs/root-test

  added / updated specs: 
    - root

The following NEW packages will be INSTALLED:

    afterimage:             1.20-hf014aae_1002                      conda-forge
    atk:                    2.25.90-hf2eb9ee_1001                   conda-forge
    binutils_impl_linux-64: 2.31.1-h6176602_1                       conda-forge
    binutils_linux-64:      2.31.1-h6176602_3                       conda-forge
    blas:                   1.1-openblas                            conda-forge
    bzip2:                  1.0.6-h14c3975_1002                     conda-forge
    ca-certificates:        2018.11.29-ha4d7672_0                   conda-forge
    cairo:                  1.14.12-h80bd089_1005                   conda-forge
    certifi:                2018.11.29-py37_1000                    conda-forge
    cfitsio:                3.430-hc04bd9f_1001                     conda-forge
    clang_variant:          1.0-cling                               conda-forge
    clangdev:               5.0.0-hdb39e3b_1001                     conda-forge
    curl:                   7.63.0-h646f8bb_1000                    conda-forge
    davix:                  0.6.8-h4da270d_1002                     conda-forge
    dbus:                   1.13.0-h4e0c4b3_1000                    conda-forge
    expat:                  2.2.5-hf484d3e_1002                     conda-forge
    fftw:                   3.3.8-h14c3975_1001                     conda-forge
    fontconfig:             2.13.1-h2176d3f_1000                    conda-forge
    freetype:               2.9.1-h3cfcefd_1004                     conda-forge
    gcc_impl_linux-64:      7.3.0-habb00fd_1                        conda-forge
    gcc_linux-64:           7.3.0-h553295d_3                        conda-forge
    gdk-pixbuf:             2.36.12-h4f1c04b_1001                   conda-forge
    gettext:                0.19.8.1-h9745a5d_1001                  conda-forge
    gfortran_impl_linux-64: 7.3.0-hdf63c60_1                                   
    gfortran_linux-64:      7.3.0-h553295d_3                                   
    giflib:                 5.1.4-h14c3975_1001                     conda-forge
    glib:                   2.56.2-had28632_1001                    conda-forge
    gobject-introspection:  1.56.1-py37h9e29830_1001                conda-forge
    graphite2:              1.3.13-hf484d3e_1000                    conda-forge
    graphviz:               2.38.0-hcf1ce16_1009                    conda-forge
    gsl:                    2.4-blas_openblash5c7cb9b_1004          conda-forge [blas_openblas]
    gst-plugins-base:       1.12.5-h3865690_1000                    conda-forge
    gstreamer:              1.12.5-h0cc0488_1000                    conda-forge
    gtk2:                   2.24.31-h5baeb44_1000                   conda-forge
    gxx_impl_linux-64:      7.3.0-hdf63c60_1                        conda-forge
    gxx_linux-64:           7.3.0-h553295d_3                        conda-forge
    harfbuzz:               1.9.0-he243708_1001                     conda-forge
    icu:                    58.2-hf484d3e_1000                      conda-forge
    jpeg:                   9c-h14c3975_1001                        conda-forge
    krb5:                   1.16.3-hc83ff2d_1000                    conda-forge
    libcroco:               0.6.12-h468c787_1001                    conda-forge
    libcurl:                7.63.0-h01ee5af_1000                    conda-forge
    libedit:                3.1.20170329-hf8c457e_1001              conda-forge
    libffi:                 3.2.1-hf484d3e_1005                     conda-forge
    libgcc-ng:              7.3.0-hdf63c60_0                        conda-forge
    libgfortran-ng:         7.3.0-hdf63c60_0                                   
    libglu:                 9.0.0-hf484d3e_1000                     conda-forge
    libiconv:               1.15-h14c3975_1004                      conda-forge
    libpng:                 1.6.36-h84994c4_1000                    conda-forge
    librsvg:                2.40.19-h84fa2a2_1000                   conda-forge
    libssh2:                1.8.0-h1ad7b7a_1003                     conda-forge
    libstdcxx-ng:           7.3.0-hdf63c60_0                        conda-forge
    libtiff:                4.0.10-h648cc4a_1001                    conda-forge
    libtool:                2.4.6-h14c3975_1002                     conda-forge
    libuuid:                2.32.1-h14c3975_1000                    conda-forge
    libxcb:                 1.13-h14c3975_1002                      conda-forge
    libxml2:                2.9.8-h143f9aa_1005                     conda-forge
    llvm-meta:              5.0.0-0                                 conda-forge
    llvmdev:                5.0.0-h6bb024c_1001                     conda-forge
    lz4:                    2.1.6-py37ha8eefa0_1000                 conda-forge
    lz4-c:                  1.8.1.2-0                               conda-forge
    ncurses:                6.1-hf484d3e_1002                       conda-forge
    numpy:                  1.16.0-py37_blas_openblash1522bff_1000  conda-forge [blas_openblas]
    openblas:               0.3.3-h9ac9557_1001                     conda-forge
    openssl:                1.0.2p-h14c3975_1002                    conda-forge
    pango:                  1.40.14-hf0c64fd_1003                   conda-forge
    pcre:                   8.41-hf484d3e_1003                      conda-forge
    pip:                    18.1-py37_1000                          conda-forge
    pixman:                 0.34.0-h14c3975_1003                    conda-forge
    pthread-stubs:          0.4-h14c3975_1001                       conda-forge
    python:                 3.7.1-hd21baee_1000                     conda-forge
    qt:                     5.6.2-hf516382_1011                     conda-forge
    readline:               7.0-hf8c457e_1001                       conda-forge
    root:                   6.14.06-py37_blas_openblash153e551_1000 conda-forge [blas_openblas]
    setuptools:             40.6.3-py37_0                           conda-forge
    sqlite:                 3.26.0-h67949de_1000                    conda-forge
    tbb:                    2019.3-h6bb024c_1000                    conda-forge
    tbb-devel:              2019.3-h6bb024c_1000                    conda-forge
    tk:                     8.6.9-h84994c4_1000                     conda-forge
    vdt:                    0.4.2-hf484d3e_1002                     conda-forge
    wheel:                  0.32.3-py37_0                           conda-forge
    xorg-fixesproto:        5.0-h14c3975_1002                       conda-forge
    xorg-kbproto:           1.0.7-h14c3975_1002                     conda-forge
    xorg-libice:            1.0.9-h14c3975_1004                     conda-forge
    xorg-libsm:             1.2.3-h4937e3b_1000                     conda-forge
    xorg-libx11:            1.6.6-h14c3975_1000                     conda-forge
    xorg-libxau:            1.0.8-h14c3975_1006                     conda-forge
    xorg-libxcursor:        1.1.15-h14c3975_1002                    conda-forge
    xorg-libxdmcp:          1.1.2-h14c3975_1007                     conda-forge
    xorg-libxext:           1.3.3-h14c3975_1004                     conda-forge
    xorg-libxfixes:         5.0.3-h14c3975_1004                     conda-forge
    xorg-libxft:            2.3.2-h6e45c93_1003                     conda-forge
    xorg-libxpm:            3.5.12-h14c3975_1002                    conda-forge
    xorg-libxrender:        0.9.10-h14c3975_1002                    conda-forge
    xorg-libxt:             1.1.5-h14c3975_1002                     conda-forge
    xorg-renderproto:       0.11.1-h14c3975_1002                    conda-forge
    xorg-xextproto:         7.3.0-h14c3975_1002                     conda-forge
    xorg-xproto:            7.0.31-h14c3975_1007                    conda-forge
    xrootd:                 4.8.5-py37h09375b9_1002                 conda-forge
    xz:                     5.2.4-h14c3975_1001                     conda-forge
    zlib:                   1.2.11-h14c3975_1004                    conda-forge

Proceed ([y]/n)? 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... + cd /home/user/conda/envs/root-test
+ export ROOTIGNOREPREFIX=1
+ ROOTIGNOREPREFIX=1
+ python /home/user/conda/envs/root-test/etc/dictpch/makepch.py /home/user/conda/envs/root-test/etc/allDict.cxx.pch -I/home/user/conda/envs/root-test/include
In file included from input_line_12:21:
In file included from ./etc/dictpch/allHeaders.h:57:
In file included from /home/user/conda/envs/root-test/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/climits:42:
In file included from /home/user/conda/envs/root-test/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/limits.h:125:
In file included from /home/user/conda/envs/root-test/etc/cling/lib/clang/5.0.0/include/limits.h:37:
/usr/include/limits.h:145:5: error: function-like macro '__GLIBC_USE' is not defined
#if __GLIBC_USE (IEC_60559_BFP_EXT)
    ^
Error: ./bin/rootcling: compilation failure (./allDictc3c32ee18d_dictUmbrella.h)

failed
Rolling back transaction: ...working... done

</details>

<br/>
Environment:
I am creating an environment with <code>conda create -n root-test -c conda-forge root -v</code>.

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : None
            shell level : 0
       user config file : /home/wshanks/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /home/user/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/conda/pkgs
                          /home/wshanks/.conda/pkgs
       envs directories : /home/user/conda/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.18.4 CPython/3.6.8 Linux/4.19.3-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by henryiii** [comment]
Are you using the GCC7 label? I don't think it has been made default yet (will be at some point today, see https://conda-forge.org/status/).

**Comment by chrisburr** [comment]
The migration should be complete so the label shouldn't be needed anymore.

@willsALMANJ Thanks for testing this out and reporting. As I'm struggling to reproduce the issue:
* What operating system are you using?
* Can you send us the output of `env`? (check there isn't any private information included before sharing)

**Comment by henryiii** [comment]
@willsALMANJ  Assuming from `conda-info`, you are using fedora 28. This worked for me in a fresh fedora38 docker instance (`docker run --rm -it fedora:28 bash`):

```bash
yum install bzip2
bash Miniconda3-latest-Linux-x86_64.sh
source /root/.bashrc
conda create -n root-test -c conda-forge root -v
conda activate root-test
root -b
```

This is Python 3.7 instead of 3.6. Any idea what might be triggering the bug in your setup?

<summary>Conda info output:<details>

```
    active environment : root-test
    active env location : /miniconda/envs/root-test
            shell level : 2
       user config file : /root/.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /miniconda/pkgs
                          /root/.conda/pkgs
       envs directories : /miniconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-514.21.2.el7.x86_64 fedora/28 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>
</summary>

**Comment by chrisburr** [comment]
I've managed to reproduce this in inside docker by installing `gcc` at the same time as `bzip2`.

Clang shouldn't be looking inside `/usr` at all but I'd missed [this in the toolchain file](https://github.com/root-project/root/blob/master/interpreter/llvm/src/tools/clang/lib/Driver/ToolChains/Linux.cpp#L702-L707). It could be added to [this list of patches](https://github.com/conda-forge/clangdev-feedstock/blob/5.x/recipe/build_clangdev.sh#L2) (note it's the 5.x branch of clangdev), though it might make more sense to just modify that file to hard code the conda's sysroot.

I'll report back once I it's (hopefully) been fixed, though it might take a few days as I'm travelling tomorrow.

**Comment by willsALMANJ** [comment]
Thanks for looking into it further! It seems like you have already gotten the information you need, but here is what I found while playing around with things. Maybe it will be helpful to someone debugging in the future.

I used `systemd-nspawn` instead of `docker` because I am more familiar with it:

```
mkdir -p $HOME/tmp/fedora/
sudo dnf --releasever=28 --installroot=$HOME/tmp/fedora/ install systemd passwd dnf fedora-release tar bzip2
sudo semanage fcontext -a -t container_file_t "$HOME/tmp/fedora(/.*)?"
sudo restorecon -R $HOME/tmp/fedora
sudo systemd-nspawn -D $HOME/tmp/fedora
```
and then inside the container:

```
curl -LO https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b
source miniconda3/etc/profile.d/conda.sh
conda install -c conda-forge -n root-test -v root
```
That installed successfully. Then I did the following:

```
dnf install glibc-headers
conda install -c conda-forge -n root-test2 -v root
```

and that failed with the error I presented above (on Fedora, `glibc-headers` is the package providing `/usr/include/limits.h`).

(For what it's worth, later I did `dnf install xorg-x11-apps` and then started the container with `sudo systemd-nspawn --setenv=DISPLAY=$DISPLAY --setenv=XAUTHORITY=$XAUTHORITY --bind-ro=/tmp/.X11-unix --bind-ro=$HOME -D fedora/` so I could test that ROOT could open graphical windows).

**Comment by willsALMANJ** [comment]
Another bit of information: in my main system, I temporarily moved `/usr/include/limits.h` somewhere else, installed `root`, and then moved `/usr/include/limits.h` back and ROOT has been working for me after that.

One other unrelated issue that I have been noticing: it seems like some conda-forge mirrors are out of date? Some of the time `conda install -c conda-forge root` works and sometimes it gives `conda.exceptions.PackagesNotFoundError` and I have to use `--offline` to get it install from the cache that it had previously downloaded when it was working.

**Comment by henryiii** [comment]
@willsALMANJ: it's good to know that's the only issue.

About the problem with the cache, I was seeing a related but different problem yesterday - on one computer, conda-forge's package list was old (missing all new additions, not just root) about 70% of the time. I finally ran `conda clean --all` and it started working, though I'm not sure if the two events were related. I think there may be some issues related to the recent major changes that might take a day or two to settle.

**Comment by chrisburr** [comment]
@willsALMANJ This should be fixed now, can you check?

(Python 2.7 and 3.7 are already deployed and 3.6 be available soon)

**Comment by willsALMANJ** [comment]
Yes, it works for me!

(Works means that `conda install -c conda-forge root` runs without error and that running this following script generates a plot without error: https://github.com/willsALMANJ/pyroot_link_to_binary/blob/master/test_pyroot.py).

**Comment by chrisburr** [comment]
Wonderful!

Thanks again for reporting, if you find any more issues let us know.
