### ISSUE TITLE
Update to 6.18

### ISSUE THREAD

**Issue by henryiii** [conda-forge/root-feedstock#38]
I've started the update process here: https://github.com/henryiii/root-feedstock/tree/henryiii-update

However, the build fails with:

```
CMake Error at cmake/modules/RootNewMacros.cmake:288 (message):
  Cannot find header MPCode.h to generate dictionary G__MultiProc for.  Did
  you forget to set the INCLUDE_DIRECTORIES property for the current
  directory?
Call Stack (most recent call first):
  cmake/modules/RootNewMacros.cmake:977 (ROOT_GENERATE_DICTIONARY)
  core/multiproc/CMakeLists.txt:5 (ROOT_STANDARD_LIBRARY_PACKAGE)


-- Configuring incomplete, errors occurred!
```

Will resume later.

**Comment by Axel-Naumann** [comment]
Very surprising - thanks for reaching out! Let's fix that.

First, I suppose you *do* have `core/multiproc/inc/MPCode.h`? Can you open a Jira ticket at https://root.cern/bugs where you share your CMakeCache.txt?

**Comment by chrisburr** [comment]
It does and done: https://sft.its.cern.ch/jira/browse/ROOT-10210
