### ISSUE TITLE
Mark 6.18.04 build 19 as broken

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root-feedstock#58]
@conda-forge/core Please can you mark the version 6.18.04 build 19 as broken (i.e. the most recent). It's split across several packages:

* [`root`](https://anaconda.org/conda-forge/root/files)
* [`root_base`](https://anaconda.org/conda-forge/root_base/files)
* [`root-binaries`](https://anaconda.org/conda-forge/root-binaries/files)
* [`root-dependencies`](https://anaconda.org/conda-forge/root-dependencies/files)

**Comment by jjhelmus** [comment]
I think I've marked them all as `broken`.  Can you verify @chrisburr

**Comment by chrisburr** [comment]
Yes, I think that's all of them. Thanks @jjhelmus! 🍰
