### ISSUE TITLE
Flags enabled in conda root?

### ISSUE THREAD

**Issue by glass-ships** [conda-forge/root-feedstock#61]
Issue:

Not so much an issue as a question about the build, but I wasn't sure where to go about asking this. 

I'm just wondering what flags are enabled when the conda version of ROOT was compiled? My collaboration has software which requires the XML and FFTW flags to be enabled, and I wasn't able to discern from the source code. 

Perhaps it could be mentioned in the README? 

Thanks!

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by henryiii** [comment]
```
root-config --features

cxx17 asimage astiff builtin_freetype builtin_ftgl builtin_gl2ps builtin_xxhash builtin_zlib clad cling cocoa davix exceptions explicitlink fftw3 fitsio gdml gviz http imt libcxx mathmore minuit2 opengl pch pythia8 python roofit webgui root7 rpath shared soversion sqlite ssl thread tmva tmva-cpu tmva-pymva vdt xml xrootd
```

I believe both are enabled.

**Comment by henryiii** [comment]
Flags are here:

https://github.com/conda-forge/root-feedstock/blob/f6148459d19e0122ebfd5fb66fc27d1479a8088f/recipe/build_root-base.sh#L62-L104

But some things enable themselves when found, based on the requirements here:

https://github.com/conda-forge/root-feedstock/blob/f6148459d19e0122ebfd5fb66fc27d1479a8088f/recipe/meta.yaml#L58-L122

**Comment by chrisburr** [comment]
@glass-ships To add, this aims to be a "complete" installation so if you find anything is missing, open and issue and we will see what we can do about it.

**Comment by glass-ships** [comment]
Excellent, thank you for the responses! Shall update if needs be.
