### ISSUE TITLE
Add `root-minimal`

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/root-feedstock#7]
Following on from #5, it might be useful to have a `root-minimal` package to further improve install times. This would be especially useful for making CI faster.

**Comment by chrisburr** [comment]
Current proposal is to split this into two packages:
 * `root-base` The current package but with almost no dependencies (`etc/allDict.pch` removed)
 * `root` A meta-package that adds every dependency

### Distributing `etc/allDict.pch`

`root-base` will depend on a feature called `root_pch` which is available in two variants that are also built in this feedstock:
 * `default` A package containing only `etc/allDict.pch` (~57 MB download)
 * `gen-pch` A package containing a post install hook that generates the PCH

`root` on Linux will depend on `gen-pch` to reduce the download size and ensure the paths inside the PCH are correct.

### Incomplete list of dependencies that can be "optional":
 * `compilers`
 * `python`
 * `pythia8`
 * `xrootd`
 * `fftw`
 * `openblas`
 * `numpy`

**Comment by oshadura** [comment]
@chrisburr I am working on similiar issue on a ROOT side. We already have a concept of root-base package which will consist of libCore, libCling and libRIO. All other ROOT components (e.g. packages) will be installable on the top of root-base and it will exactly resolve this issue. I will keep on posting on a progress of development.

**Comment by willsALMANJ** [comment]
You might also look at [how Fedora packages ROOT](https://src.fedoraproject.org/rpms/root/blob/master/f/root.spec). I don't know that you want to go that extreme but it splits things into literally 100 packages.

**Comment by delaossa** [comment]
Hello, 
I think that it is really practical to be able to install just a minimal version of ROOT from conda-forge 
Is this already possible? How will that work?
Thanks!

**Comment by chrisburr** [comment]
Hi @delaossa! A minimal ROOT package is not currently available and I'm inclined to wait for @oshadura's developments with official support for modules rather than coming up with a "hacky" way of making this work.

Is there a reason the full package is not suitable for your use case? If there is I'm happy to think about an interim solution.

**Comment by delaossa** [comment]
Hi @chrisburr and thanks for the quick answer. I haven't checked if the full package works yet because it is still installing (over an hour now). I guess and hope that it will work OK. 

I agree that it is definitely preferable to wait for @oshadura if the solution is going to be more robust. 
Should I understand that they are trying to achieve a modular ROOT also for the classic version?Cheers.

**Comment by chrisburr** [comment]
Assuming you have a good internet connection it should only take 5-10 minutes.

Can you share which commands you ran and which stage it is stuck on?

**Comment by delaossa** [comment]
Hello, I confirm that the installation takes about 5 minutes in a local machine (my laptop).
For some reason when performing the installation in a cluster machine, the installation takes a way longer (around 12 minutes).

**Comment by chrisburr** [comment]
Do you know what filesystem your cluster uses? I suspect it is being slowed down by the IO performance.

**Comment by willsALMANJ** [comment]
Were the slow installs into a clean environment? I have been seeing really slow resolution of packages when using conda-forge recently related to the issues described here: https://www.anaconda.com/understanding-and-improving-condas-performance/
