### ISSUE TITLE
Build for windows

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/root-feedstock#95]
Is it feasible to try and update the recipe to build on windows? Is that platform supported by the upstream developers?

**Comment by chrisburr** [comment]
ROOT does [have "preview" releases](https://root.cern/content/release-62004) for Windows but last I heard it wasn't possible to build for 64 bit Windows due to hard to fix issues in cling. That said conda-forge [does have 64-bit Windows binaries for vanilla `cling`](https://github.com/conda-forge/cling-feedstock) so I'm not sure what actually blocks it. I'll ask.

**Comment by chrisburr** [comment]
From the ROOT team:

> There is no ROOT build on Win64, which is not supported for the time being. It requires deep changes in ROOT, due to pointer to long casting (the long type is 32 bit on Win64...)

I'm going to close this for now. If someone is interested enough to try and get it working I'm happy to reopen this issue and support the effort.

I do know quite a few people that use Windows Subsystem for Linux with the Linux conda-forge binaries so maybe that is an option for you use case?

Alternatively, if you only need to be able to read/write ROOT files, [`uproot`](https://github.com/scikit-hep/uproot) is an excellent alternative which supports effectively any platform.

**Comment by duncanmmacleod** [comment]
Thanks @chrisburr; I am interested in building out a scientific (LIGO/GW) stack on Windows mainly to aid in outreach and teaching (effectively 'all' of which happens on windows) - and WSL isn't reliable enough yet (as far as I have seen).

`uproot` is the best solution for most cases (postprocessing etc), so I'll look more into that.

Thanks again.

**Comment by chrisburr** [comment]
I've used WSL last october for a workshop teaching new PhD students, where their laptops were a roughly even mixture of Windows/macOS/Linux. It worked well but it's a bit heavy for outreach.

I've seen JSROOT work well for this kind of thing and it's really nice being able to do everything from within a static webpage: https://root.cern.ch/js/

**Comment by henryiii** [comment]
Note that WSL 2 is now out. And next they plan to integrate graphics with [GPU acceleration support](https://www.theverge.com/2020/5/19/21263377/microsoft-windows-10-linux-gui-apps-gpu-acceleration-wsl-features). They are also adding a [windows package manager.](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/)

Medium article: https://towardsdatascience.com/dual-boot-is-dead-windows-and-linux-are-now-one-27555902a128

**Comment by bellenot** [comment]
@chrisburr FYI, ROOT builds and is available on Windows x64 since quite a while now...

**Comment by dertexaner** [comment]
Just pinging here as well (https://conda.discourse.group/t/windows-installers-for-root/568/3)

Would it be possible to add windows installers to [https://anaconda.org/conda-forge/root/ 1](https://anaconda.org/conda-forge/root/) given that ROOT now builds on Windows x64  ?
This would be a huge help for teaching purposes where students have a mix of operating systems including Windows.

Thanks!
